apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetescode
  labels:
    app: kubernetescode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetescode
  template:
    metadata:
      labels:
        app: kubernetescode
    spec:
      containers:
      - name: kubernetescode
        image: ganeshkarthik/test:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: kubernetescode
spec:
  selector:
    app: kubernetescode
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 31110
